function Quotes = import_quotes_csv(filename, formatSpec, headers, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   Quotes = import_quotes_csv(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   Quotes = import_quotes_csv(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   Quotes = import_quotes_csv('NASDAQ_19921231.csv', 2, 252);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/09/05 14:30:52

%% Initialize variables.
delimiter = ',';
if nargin<=4
    startRow = 2;
    endRow = inf;
end

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
Quotes = table(dataArray{1:end-1}, 'VariableNames', headers);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% Quotes.Date=datenum(Quotes.Date);
